name: .NET

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/README.md'
  release:
    branches: [main]
    types: [published]
    
env:
  BUILD_DIR: build
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Semantic Version
      uses: ncipollo/semantic-version-action@v1
      id: git_version
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      env:
        BUILD_VERSION: ${{ format('{0}.{1}.{2}.{3}', steps.git_version.outputs.major, steps.git_version.outputs.minor, steps.git_version.outputs.patch, github.run_number) }}
      run: dotnet build -c Release -o $env:BUILD_DIR -p:Version=$env:BUILD_VERSION --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        path: ${{ env.BUILD_DIR }}
    - name: Zip Release
      uses: vimtor/action-zip@v1
      if: ${{ github.event_name == 'Release' }}
      with:
        files: |
          ${{ env.BUILD_DIR }}
          LICENSE
        dest: ${{ format('MsiFinder_{0}.zip', github.ref) }}
    - name: Upload Release
      uses: svenstaro/upload-release-action@2.2.1
      if: ${{ github.event_name == 'Release' }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: '*.zip'
        file_glob: true
        overwrite: true
