name: .NET

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/README.md'
  release:
    branches: [main]
    types: [published]
    
env:
  BUILD_DIR: build
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Git Version
      uses: PaulHatch/semantic-version@v4.0.2
      id: git_version
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      env:
        BUILD_VERSION: ${{ steps.git_version.outputs.version }}
      run: dotnet build -c Release -o $env:BUILD_DIR -p:Version=$env:BUILD_VERSION --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Zip
      uses: vimtor/action-zip@v1
      with:
        files: ${{ env.BUILD_DIR }}
        dest: ${{ format('MsiFinder_v{0}', steps.git_version.outputs.version) }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        path: '*.zip'
    - name: Release
      uses: svenstaro/upload-release-action@2.2.1
      if: ${{ github.event_name == 'Release' }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: '*.zip'
        file_glob: true
        overwrite: true
